In [12]:
import torch
from torch import nn
from torch.nn import ReLU, Sigmoid

In [3]:
input = torch.tensor([[1,-0.5],
                      [-1, 3]])
# 注意输入需要的数据形状
input = torch.reshape(input, (-1, 1, 2, 2))
print(input.shape)

torch.Size([1, 1, 2, 2])


In [10]:
class ReLUActivationModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.relu1 = ReLU(inplace=False)  # inplace 是否在原来的变量进行替换

    def forward(self, input):
        output = self.relu1(input)
        return output


In [11]:
relu = ReLUActivationModel()
output = relu(input)    # ReLU 小于0的数全部变为0  对图像处理不明显
print(input)
print(output)

tensor([[[[ 1.0000, -0.5000],
          [-1.0000,  3.0000]]]])
tensor([[[[1., 0.],
          [0., 3.]]]])


In [13]:
class SigmoidModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.sigmoid = Sigmoid()

    def forward(self, input):
        return self.sigmoid(input)

In [14]:
sigmoid = SigmoidModel()
output1 = sigmoid(input)
print(input)
print(output1)

tensor([[[[ 1.0000, -0.5000],
          [-1.0000,  3.0000]]]])
tensor([[[[0.7311, 0.3775],
          [0.2689, 0.9526]]]])


In [15]:
from torch.utils.data import DataLoader
import torchvision

dataset = torchvision.datasets.CIFAR10("CIFAR10", train=False, transform=torchvision.transforms.ToTensor(), download=True)

dataloader = DataLoader( dataset,batch_size=64)

Files already downloaded and verified


In [16]:
from torch.utils.tensorboard import  SummaryWriter

writer = SummaryWriter('logs')

In [18]:
step = 0
model = SigmoidModel()
for data in dataloader:
    imgs, targets = data
    # torch.Size([64, 3, 32, 32])
    # print(imgs.shape)
    writer.add_images("sig_input", imgs, step)
    output = model(imgs)
    writer.add_images("sig_output", output, step)
    step = step + 1
    # torch.Size([64, 3, 32, 32])
    # print(output.shape)
    break

- Sigmoid: 图像变为灰色