In [5]:
from torch import nn
import torch

In [6]:
# 定义模型

class MyModel(nn.Module):
    def __init__(self):
        super().__init__()   # 调用父类进行初始化
        
    def forward(self, input):  # input 神经网络的输入
        output = input + 1
        return output          # 神经网络的输出

In [9]:
# 调用神经网络
model = MyModel()
# x = 1.0
x = torch.tensor(1.0)  # 输入
output = model(x)      # 使用神经网络
print(output)

tensor(2.)


## 卷积操作  Convolution Layers

In [10]:
data = [[1,2,0,3,1],
       [0,1,2,3,1],
       [1,2,1,0,0],
       [5,2,3,1,1,],
       [2,1,0,1,1]]

# 输入图像矩阵：张量（5*5）
input = torch.tensor(data)

print(input)

tensor([[1, 2, 0, 3, 1],
        [0, 1, 2, 3, 1],
        [1, 2, 1, 0, 0],
        [5, 2, 3, 1, 1],
        [2, 1, 0, 1, 1]])


In [11]:
# 卷积核(3*3)
kernel = torch.tensor([[1,2,1],
                      [0,1,0],
                      [2,1,0]])

print(kernel)

tensor([[1, 2, 1],
        [0, 1, 0],
        [2, 1, 0]])


In [ ]:
# 卷积操作
torch.nn.Conv2d(in_channels, # 输入 具有尺寸要求
                out_channels,# 输出 具有尺寸要求
                kernel_size, # 卷积核大小
                stride=1, 
                padding=0, 
                dilation=1, 
                groups=1,
                bias=True, 
                padding_mode='zeros', 
                device=None, 
                dtype=None)

In [13]:
print(input.shape)
print(kernel.shape)

torch.Size([5, 5])
torch.Size([3, 3])


In [15]:
# 变换尺寸
input = torch.reshape(input, (1,1,5,5))  # batch size, number of channels, height, widdth
kernel= torch.reshape(kernel, (1,1,3,3))
print(input.shape)
print(kernel.shape)

torch.Size([1, 1, 5, 5])
torch.Size([1, 1, 3, 3])


In [16]:
# 卷积
import torch.nn.functional as F

# 卷积结果
output = F.conv2d(input, kernel, stride=1)
print(output)

tensor([[[[10, 12, 12],
          [18, 16, 16],
          [13,  9,  3]]]])


In [17]:
output2 = F.conv2d(input, kernel, stride=2)
print(output2)

tensor([[[[10, 12],
          [13,  3]]]])


In [18]:
# padding 填充数据，默认不进行填充
output3 = F.conv2d(input, kernel, stride=1,padding=1)  # 以0进行填充
print(output3)

tensor([[[[ 1,  3,  4, 10,  8],
          [ 5, 10, 12, 12,  6],
          [ 7, 18, 16, 16,  8],
          [11, 13,  9,  3,  4],
          [14, 13,  9,  7,  4]]]])
